CREATE TABLE User(
  id INT PRIMARY KEY AUTO_INCREMENT, 
  username VARCHAR(50) NOT NULL, 
  email VARCHAR(50) UNIQUE NOT NULL, 
  password VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  full_name  VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE
);



